version: '3.8'

services:
  db:
    image: postgres
    container_name: db_1
    environment:
      - POSTGRES_USER=$SPRING_DATASOURCE_USERNAME
      - POSTGRES_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - "$DB_PORT:5432"
